destination: production
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    smart_quotes: ["apos", "apos", "quot", "quot"]
paginate_path: "blog/page/:num"
paginate: 2
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
